site_name: "Antoine Chevrot"
site_url: "https://achevrot.github.io/"
site_description: "Research, publications, projects, teaching, contact"

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: black
      accent: pink
  icon:
    repo: fontawesome/brands/github

repo_url: "https://github.com/achevrot"
repo_name: "achevrot"

extra_css:
  - assets/css/synthwave.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/achevrot
      name: GitHub

nav:
  - Home: index.md
  - About: about.md
  - Publications: publications.md
  - Projects: projects.md
  - Teaching: teaching.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list